//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Sanscs.QuestionImport
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Sanscs.Model;

    public interface IQuestionResolver<TIn, TOut> : IResolver<TIn, TOut>
	{
	}
}

